export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILED = 'GET_PHOTOS_FAILED';
export const YEARS_READY = 'YEARS_READY';
//export const SET_YEAR = 'SET_YEAR';
